#!/bin/sh


# start some nice programs
test $(which gpg-agent) && eval $(gpg-agent --daemon)

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# gnome-keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

xset r rate 300 50 &                      # Speed xrate up
setxkbmap -option caps:escape             # run the remaps script, switching caps/esc and more; check it for more info
# mpd &                                     # music player daemon-you might prefer it as a service though
feh --bg-center ~/.local/share/wall.jpg & # set the background with the `setbg` script
xcompmgr &                                # xcompmgr for transparency
dunst &                                   # dunst for notifications
# redshift -c $HOME/.config/redshift/redshift.conf &
slstatus &


# third-party apps
if [ $(which udisksctl) ]; then
  if [ $(which udiskie) ]; then
    udiskie -ANt &
  fi
fi

# third-party apps
if [ $(which dropbox) ]; then
  dropbox &                               # dropbox, cloud storage
fi

# source machine- and uname-specific xinitrcs
xinitcfg="$HOME/.config/xinit"
test -f "$xinitcfg/u/$(uname)"       && . "$xinitcfg/u/$(uname)"
test -f "$xinitcfg/host/$(hostname)" && . "$xinitcfg/host/$(hostname)"

ssh-agent dwm 2>>/tmp/dwm_log || break

# exit X when slstatus (or failsafe xterm) is killed
if [ $(which slstatus) ]; then
    slstatus
elif [ $(which st) ]; then
    st
elif [ $(which xterm) ]; then
    xterm -ls -T Failsafe -geometry 80x24-0-0
fi